# Setting
gpus: 0
seed: 2561
debug: False
pretrained_path:
work_dir: ./workdir
no_progress_bar: False

tcr: 4
tcl: Mta2Wrapper-ST2LiteMBConv
datasetCode: 3mdad-rgb2
configCode: 2561
device: 0
gcmh: 3
# dataset="3mdad-rgb2"
# echo "====> ${dataset}  ====>  ${TCLayer} ====>  ${tcr}  =="
# python3 ../main_softnode2_fixed_vs.py --device ${device}  --configCode ${configCode}   --datasetCode ${dataset} \
#              -tcl  Mta2Wrapper-${TCLayer}    -tcr ${tcr}  -ad -ws  --extract   --visualize  -gcmh 3  \
#              --visualization_frames  1 3 5 7 9 11 13 15 17  --visualization_sample 3

# Visualization
visualization_class: 0
visualization_sample: 3
visualization_frames: [ 1,3,5,7,9,11,13 ]

# Data Loader
dataset: 3mdad_downsampled2
dataset_args:
  3mdad_downsampled2:
    train_batch_size: 16
    eval_batch_size: 16
    num_frame: 50
    inputs: JVB
    transform: False
    #    root_folder: /public/home/chen_ai/lixutong/projects/coldnight/n3_storage/data_advanced_splitrgb1/3mdad/clip50/RGB2/
    #    root_folder: /home/bullet/PycharmProjects/LowlightRecognition/coldnight/n3_storage/data_advanced_splitrgb1/3mdad/clip50/RGB2/
    #    root_folder: /home/bullet/PycharmProjects/LowlightRecognition/coldnight/n3_storage/data_advanced_splitrgb1_0315/3mdad/clip50/RGB2/
    #    root_folder: /home/bullet/PycharmProjects/LowlightRecognition/coldnight/n3_storage/data_advanced_splitrgb1_0316_softnode2_fixed/3mdad/clip50/RGB2/
    #    root_folder: /home/bullet/PycharmProjects/LowlightRecognition/coldnight/n3_storage/data_advanced_splitrgb1_0316_softnode3/3mdad/clip50/RGB2/
    root_folder: P:\bullet\LowlightRecognition\coldnight\n3_storage\data_advanced_splitrgb1_0316_softnode3\3mdad\clip50\RGB2\

# Model
model_type: EfficientGCN-B0
model_args:
  stem_channel: 64
  block_args: [ [ 48,1,0.5 ],[ 24,1,0.5 ],[ 64,2,1 ],[ 128,2,1 ] ]
  fusion_stage: 2
  act_type: swish
  att_type: stja
  layer_type: Sep
  drop_prob: 0.25
  kernel_size: [ 5,2 ]
  scale_args: [ 1.2,1.35 ]
  expand_ratio: 2
  reduct_ratio: 4
  bias: True
  edge: True

# Optimizer
# SGD, Adam
optimizer: SGD
optimizer_args:
  SGD:
    lr: 0.1
    momentum: 0.9
    nesterov: True
    weight_decay: 0.0002
  Adam:
    lr: 0.1
    betas: [ 0.9,0.99 ]
    weight_decay: 0.0002

# Scheduler
# step, cosine
lr_scheduler: cosine
scheduler_args:
  step:
    max_epoch: 50
    warm_up: 0
    step_lr: [ 20,50 ]
  cosine:
    max_epoch: 50
    warm_up: 0
